import sys
sys.stdout.reconfigure(encoding='utf-8', errors='replace')
sys.stderr.reconfigure(encoding='utf-8', errors='replace')

import os
import time
import base64
import traceback
from datetime import datetime

import requests
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import (
    TimeoutException, NoSuchElementException, ElementClickInterceptedException,
    StaleElementReferenceException
)
from webdriver_manager.chrome import ChromeDriverManager

# ── Config ──────────────────────────────────────────────────────────────
BASE = "https://test-empcloud.empcloud.com"
ADMIN_EMAIL = "ananya@technova.in"
ADMIN_PASS = "Welcome@123"
SS_DIR = r"C:\Users\Admin\screenshots"
GH_TOKEN = "$GITHUB_TOKEN"
GH_REPO = "EmpCloud/EmpCloud"
os.makedirs(SS_DIR, exist_ok=True)

bugs = []
results = []
ss_num = 0


def mk_driver():
    opts = Options()
    opts.binary_location = r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"
    for a in ["--headless=new", "--no-sandbox", "--disable-dev-shm-usage",
              "--window-size=1920,1080", "--disable-gpu", "--disable-extensions",
              "--ignore-certificate-errors"]:
        opts.add_argument(a)
    svc = Service(ChromeDriverManager().install())
    d = webdriver.Chrome(service=svc, options=opts)
    d.implicitly_wait(3)
    return d


def ss(driver, name):
    global ss_num
    ss_num += 1
    fname = f"{ss_num:02d}_{name}.png"
    path = os.path.join(SS_DIR, fname)
    driver.save_screenshot(path)
    print(f"  [SS] {fname}")
    return path


def log(name, status, detail=""):
    results.append({"test": name, "status": status, "detail": detail})
    print(f"  [{status}] {name}" + (f" -- {detail}" if detail else ""))


def bug(title, desc, ss_path=None):
    hdr = {"Authorization": f"token {GH_TOKEN}", "Accept": "application/vnd.github.v3+json"}
    img_md = ""
    if ss_path and os.path.isfile(ss_path):
        try:
            with open(ss_path, "rb") as f:
                b64 = base64.b64encode(f.read()).decode()
            ts = datetime.now().strftime("%Y%m%d_%H%M%S")
            rp = f"screenshots/{ts}_{os.path.basename(ss_path)}"
            r = requests.put(f"https://api.github.com/repos/{GH_REPO}/contents/{rp}",
                             headers=hdr, json={"message": f"Upload {os.path.basename(ss_path)}",
                                                "content": b64, "branch": "main"}, timeout=30)
            if r.status_code in (200, 201):
                dl = r.json().get("content", {}).get("download_url", "")
                if dl:
                    img_md = f"\n\n### Screenshot\n![screenshot]({dl})\n"
            else:
                print(f"    [WARN] SS upload HTTP {r.status_code}")
        except Exception as e:
            print(f"    [WARN] SS upload err: {e}")

    body = desc + img_md + "\n\n---\n_Auto-generated by E2E test suite_"
    r = requests.post(f"https://api.github.com/repos/{GH_REPO}/issues",
                      headers=hdr, json={"title": title, "body": body, "labels": ["bug"]}, timeout=30)
    if r.status_code == 201:
        url = r.json().get("html_url", "")
        print(f"    [BUG] {url}")
        bugs.append({"title": title, "url": url})
    else:
        print(f"    [WARN] Issue create HTTP {r.status_code}: {r.text[:200]}")


def click(driver, el):
    try:
        el.click()
    except ElementClickInterceptedException:
        driver.execute_script("arguments[0].click();", el)


def wait(driver, sec=2):
    time.sleep(sec)
    try:
        WebDriverWait(driver, 10).until(lambda d: d.execute_script("return document.readyState") == "complete")
    except:
        pass
    time.sleep(1)


def goto(driver, path):
    driver.get(BASE + path)
    wait(driver)


def page_has(driver, *words):
    src = driver.page_source.lower()
    return any(w in src for w in words)


def body_text(driver):
    return driver.find_element(By.TAG_NAME, "body").text


def headings(driver):
    return [h.text.strip() for h in driver.find_elements(By.CSS_SELECTOR, "h1, h2, h3") if h.is_displayed() and h.text.strip()]


# ── LOGIN ───────────────────────────────────────────────────────────────
def do_login(driver):
    print("\n=== LOGIN ===")
    driver.get(BASE)
    wait(driver)
    ss(driver, "login_page")
    try:
        ef = driver.find_element(By.CSS_SELECTOR, "input[type='email']")
        pf = driver.find_element(By.CSS_SELECTOR, "input[type='password']")
        ef.clear(); ef.send_keys(ADMIN_EMAIL)
        pf.clear(); pf.send_keys(ADMIN_PASS)
        ss(driver, "login_filled")
        for b in driver.find_elements(By.TAG_NAME, "button"):
            if "sign in" in (b.text or "").lower():
                click(driver, b); break
        time.sleep(5); wait(driver)
        ss(driver, "post_login")
        if "sign in" in driver.page_source.lower() and "login" in driver.current_url.lower():
            log("Login", "FAIL", "Still on login page")
            return False
        log("Login", "PASS", f"URL: {driver.current_url}")
        return True
    except Exception as e:
        ss(driver, "login_err")
        log("Login", "FAIL", str(e)[:100])
        return False


# ── EMPLOYEE LIST ───────────────────────────────────────────────────────
def test_emp_list(driver):
    print("\n=== EMPLOYEE LIST ===")
    goto(driver, "/employees")
    s = ss(driver, "emp_list")
    hs = headings(driver)
    rows = driver.find_elements(By.CSS_SELECTOR, "table tbody tr")
    if "Employee Directory" in hs and rows:
        names = []
        for r in rows[:5]:
            tds = r.find_elements(By.TAG_NAME, "td")
            if tds:
                names.append(tds[0].text.strip().replace('\n', ' ')[:35])
        log("Employee list loads", "PASS", f"{len(rows)} employees: {names}")
    elif rows:
        log("Employee list loads", "PASS", f"{len(rows)} rows found")
    else:
        log("Employee list loads", "FAIL", f"No rows. Headings: {hs}")
        bug("[High] Employee Directory shows no employees",
            "## Description\n/employees loads but no employee rows.\n\n## Steps\n1. Login as Org Admin\n2. Go to /employees\n\n## Expected\nList of employees.\n\n## Actual\nNo data.", s)


# ── EMPLOYEE SEARCH ─────────────────────────────────────────────────────
def test_emp_search(driver):
    print("\n=== EMPLOYEE SEARCH ===")
    goto(driver, "/employees")
    time.sleep(1)

    search = None
    for sel in ["input[placeholder*='earch']", "input[placeholder*='Search']",
                "input[type='search']", "input[placeholder*='name']"]:
        try:
            el = driver.find_element(By.CSS_SELECTOR, sel)
            if el.is_displayed():
                search = el; break
        except NoSuchElementException:
            pass

    if not search:
        # Try all visible inputs
        for inp in driver.find_elements(By.CSS_SELECTOR, "input"):
            if inp.is_displayed():
                ph = (inp.get_attribute("placeholder") or "")
                itype = (inp.get_attribute("type") or "")
                if itype not in ("hidden", "password"):
                    print(f"  Input: type={itype} ph='{ph}'")

    rows_before = len(driver.find_elements(By.CSS_SELECTOR, "table tbody tr"))

    if not search:
        s = ss(driver, "search_missing")
        log("Employee search", "FAIL", "No search input found")
        bug("[Medium] Employee Directory has no search/filter input",
            "## Description\nNo search or filter input on /employees.\n\n## Steps\n1. Login as Org Admin\n2. Go to /employees\n3. Look for search box\n\n## Expected\nSearch input to filter employees.\n\n## Actual\nNo search input.", s)
        return

    log("Search input found", "PASS", f"Rows before: {rows_before}")

    # Search 'Priya'
    search.clear()
    search.send_keys("Priya")
    time.sleep(3)
    s1 = ss(driver, "search_priya")
    rows_after = len(driver.find_elements(By.CSS_SELECTOR, "table tbody tr"))

    if rows_after < rows_before:
        log("Search 'Priya'", "PASS", f"Filtered {rows_before} -> {rows_after}")
    else:
        log("Search 'Priya'", "FAIL", f"NOT filtered: {rows_before} -> {rows_after}")
        bug("[Medium] Employee search does not filter results",
            f"## Description\nSearch on Employee Directory does not filter. Typing 'Priya' leaves all {rows_before} rows.\n\n## Steps\n1. Login as Org Admin\n2. Go to /employees\n3. Type 'Priya' in search\n\n## Expected\nList filters to matching employees.\n\n## Actual\nAll {rows_after} rows remain.", s1)

    # Search nonsense
    search.clear(); search.send_keys("ZzzNonExist999"); time.sleep(3)
    s2 = ss(driver, "search_nonsense")
    rows_none = len(driver.find_elements(By.CSS_SELECTOR, "table tbody tr"))
    if rows_none == 0 or rows_none < rows_before:
        log("Search nonsense", "PASS", f"Reduced to {rows_none}")
    else:
        log("Search nonsense", "FAIL", f"Still {rows_none} rows for gibberish")

    search.clear(); time.sleep(1)


# ── EMPLOYEE PROFILE ────────────────────────────────────────────────────
def test_emp_profile(driver):
    print("\n=== EMPLOYEE PROFILE ===")
    goto(driver, "/employees")
    time.sleep(1)

    # Get actual employee link hrefs
    emp_links = []
    for a in driver.find_elements(By.CSS_SELECTOR, "a[href*='/employees/']"):
        href = a.get_attribute("href") or ""
        if "/employees/" in href and href != BASE + "/employees" and href != BASE + "/employees/":
            emp_links.append((a, href, a.text.strip().replace('\n', ' ')[:40]))

    if emp_links:
        print(f"  Found {len(emp_links)} employee links")
        for _, href, txt in emp_links[:3]:
            print(f"    '{txt}' -> {href}")

    # Try clicking the first employee link
    clicked = False
    click_url = ""
    emp_name = ""
    if emp_links:
        a_el, href, emp_name = emp_links[0]
        click_url = href
        print(f"  Clicking: '{emp_name}' -> {href}")
        click(driver, a_el)
        time.sleep(3); wait(driver)
        s = ss(driver, "emp_profile_click")

        if driver.current_url == href or "/employees/" in driver.current_url and driver.current_url != BASE + "/employees":
            log("Employee profile (click)", "PASS", f"Navigated to {driver.current_url}")
            clicked = True
        else:
            log("Employee profile (click)", "FAIL", f"Link was {href} but URL is {driver.current_url}")
            bug("[High] Employee link click does not navigate to profile",
                f"## Description\nClicking employee '{emp_name}' link (href={href}) does not navigate to the profile. URL stays at {driver.current_url}.\n\n## Steps\n1. Login as Org Admin\n2. Go to /employees\n3. Click on '{emp_name}' (link to {href})\n\n## Expected\nBrowser navigates to {href} showing employee profile.\n\n## Actual\nURL is {driver.current_url}. No navigation occurs.", s)

    # Try direct URL navigation to the employee
    if emp_links and not clicked:
        _, href, emp_name = emp_links[0]
        emp_id = href.rstrip("/").split("/")[-1]
        profile_url = f"/employees/{emp_id}"
        print(f"  Trying direct nav to {profile_url}")
        goto(driver, profile_url)
        s = ss(driver, "emp_profile_direct")
        bt = body_text(driver)

        if "employee not found" in bt.lower():
            log("Employee profile (direct)", "FAIL", f"/employees/{emp_id} -> 'Employee not found'")
            bug(f"[High] Employee profile page shows 'Employee not found' for valid ID",
                f"## Description\nNavigating directly to /employees/{emp_id} shows 'Employee not found' despite the employee existing in the directory.\n\n## Steps\n1. Login as Org Admin\n2. Go to /employees - employee '{emp_name}' is listed with link to /employees/{emp_id}\n3. Navigate to /employees/{emp_id}\n\n## Expected\nEmployee profile page for '{emp_name}'.\n\n## Actual\n'Employee not found' message displayed.", s)
        elif emp_name.split()[0].lower() in bt.lower() or "profile" in bt.lower():
            log("Employee profile (direct)", "PASS", f"Profile loaded for {emp_name}")
            test_profile_tabs(driver)
            return
        else:
            hs = headings(driver)
            log("Employee profile (direct)", "WARN", f"Page loaded but unclear content. Headings: {hs}")

    # Fallback: try another employee or a known working pattern
    if not clicked and len(emp_links) > 1:
        _, href, emp_name = emp_links[1]
        emp_id = href.rstrip("/").split("/")[-1]
        print(f"  Trying second employee: {emp_name} ({emp_id})")
        goto(driver, f"/employees/{emp_id}")
        s = ss(driver, "emp_profile_second")
        bt = body_text(driver)
        if "employee not found" not in bt.lower() and "directory" not in bt.lower():
            log("Employee profile (2nd)", "PASS", f"Profile for {emp_name}")
            test_profile_tabs(driver)
            return
        else:
            log("Employee profile (2nd)", "FAIL", f"Also failed for {emp_name}")

    # No profile loaded - skip tabs
    if not clicked:
        log("Employee profile tabs", "WARN", "Skipped - could not load any profile")


def test_profile_tabs(driver):
    print("\n=== PROFILE TABS ===")
    # On the profile page, look for tab elements
    tab_kw = ["personal", "job", "document", "bank", "salary", "leave", "attendance",
              "asset", "education", "emergency", "contact", "experience", "overview",
              "detail", "info", "history", "compensation", "statutory", "letter"]

    tabs = []
    for sel in ["[role='tablist'] [role='tab']", "[role='tablist'] button",
                "[role='tablist'] a", ".tabs button", ".tabs a",
                "[class*='TabList'] button", "[class*='tab-bar'] button",
                "[class*='tab-bar'] a"]:
        try:
            for e in driver.find_elements(By.CSS_SELECTOR, sel):
                if e.is_displayed() and e.text.strip():
                    tabs.append(e)
        except:
            pass

    # Deduplicate
    seen = set()
    unique = []
    for t in tabs:
        txt = t.text.strip()
        if txt not in seen:
            seen.add(txt)
            unique.append(t)

    # Also look for navigation links that look like tabs (horizontal)
    if not unique:
        # Maybe tabs are rendered as links/buttons in a horizontal bar
        for el in driver.find_elements(By.CSS_SELECTOR, "nav a, nav button"):
            txt = el.text.strip().lower()
            if el.is_displayed() and any(kw in txt for kw in tab_kw) and txt not in seen:
                seen.add(el.text.strip())
                unique.append(el)

    if not unique:
        s = ss(driver, "profile_no_tabs")
        log("Profile tabs", "WARN", "No tabs found")
        bug("[Medium] Employee profile page has no tabs (Personal, Job, Documents, etc.)",
            "## Description\nThe employee profile page does not display any tabs for Personal, Job, Documents, etc.\n\n## Steps\n1. Login as Org Admin\n2. Navigate to an employee profile\n\n## Expected\nTabs like Personal, Job, Documents, Bank, etc.\n\n## Actual\nNo tabs visible on the profile page.", s)
        return

    print(f"  Tabs: {[t.text.strip() for t in unique]}")
    clicked = []
    for tab in unique[:8]:
        txt = tab.text.strip()
        try:
            click(driver, tab)
            time.sleep(2)
            s = ss(driver, f"tab_{txt.replace(' ', '_').lower()[:20]}")
            clicked.append(txt)
            if page_has(driver, "server error", "500 internal", "something went wrong"):
                log(f"Tab: {txt}", "FAIL", "Error on tab")
                bug(f"[High] Employee profile '{txt}' tab error",
                    f"## Description\nThe '{txt}' tab shows an error.\n\n## Steps\n1. Open employee profile\n2. Click '{txt}' tab\n\n## Expected\nTab content loads.\n\n## Actual\nError displayed.", s)
            else:
                log(f"Tab: {txt}", "PASS")
        except Exception as e:
            log(f"Tab: {txt}", "FAIL", str(e)[:60])

    log("Profile tabs summary", "PASS" if clicked else "FAIL", f"{clicked}")


# ── ADD EMPLOYEE ────────────────────────────────────────────────────────
def test_add_emp(driver):
    print("\n=== ADD EMPLOYEE ===")
    goto(driver, "/employees")
    time.sleep(1)

    # List all interactive elements to find add button
    all_els = []
    for el in driver.find_elements(By.CSS_SELECTOR, "button, a"):
        if el.is_displayed():
            txt = el.text.strip()
            href = (el.get_attribute("href") or "")
            aria = (el.get_attribute("aria-label") or "")
            title_a = (el.get_attribute("title") or "")
            loc = el.location
            size = el.size
            all_els.append((el, txt, href, aria, title_a, loc, size))

    # Strategy 1: find by text
    add_btn = None
    for el, txt, href, aria, title_a, loc, size in all_els:
        ltxt = txt.lower()
        if any(w in ltxt for w in ["add employee", "new employee", "create employee", "invite"]):
            add_btn = el; break

    # Strategy 2: find by aria-label or title
    if not add_btn:
        for el, txt, href, aria, title_a, loc, size in all_els:
            if any(w in aria.lower() for w in ["add employee", "new", "create"]):
                add_btn = el; break
            if any(w in title_a.lower() for w in ["add employee", "new", "create"]):
                add_btn = el; break

    # Strategy 3: the FAB (floating action button) - round button at bottom-right
    fab = None
    for el, txt, href, aria, title_a, loc, size in all_els:
        x, y = loc.get("x", 0), loc.get("y", 0)
        w, h = size.get("width", 0), size.get("height", 0)
        if x > 1700 and y > 700 and 40 <= w <= 80 and 40 <= h <= 80:
            fab = el
            print(f"  FAB found at ({x},{y}) size=({w},{h}) text='{txt}' aria='{aria}'")
            break

    # Strategy 4: try direct URL (only if no add_btn and no fab)
    form_found = False
    if not add_btn and not fab:
        for path in ["/employees/add", "/employees/new", "/employees/create"]:
            goto(driver, path)
            time.sleep(2)
            inputs = [i for i in driver.find_elements(By.CSS_SELECTOR, "input:not([type='hidden'])") if i.is_displayed()]
            hs = headings(driver)
            bt = body_text(driver).lower()
            if len(inputs) >= 3 and ("add" in bt or "create" in bt or "new" in bt or "employee" in " ".join(hs).lower()):
                s = ss(driver, "add_emp_form_direct")
                log("Add employee form (direct URL)", "PASS", f"{len(inputs)} inputs at {path}")
                fill_add_form(driver, inputs)
                form_found = True
                break

    if form_found:
        return

    # Try clicking FAB - re-find it to avoid stale reference
    if fab and not add_btn:
        # Re-navigate to /employees and re-find the FAB
        goto(driver, "/employees")
        time.sleep(2)
        for el in driver.find_elements(By.CSS_SELECTOR, "button, a"):
            if el.is_displayed():
                loc = el.location
                sz = el.size
                x, y = loc.get("x", 0), loc.get("y", 0)
                w, h = sz.get("width", 0), sz.get("height", 0)
                if x > 1700 and y > 700 and 40 <= w <= 80 and 40 <= h <= 80:
                    add_btn = el
                    break

    if add_btn:
        try:
            btn_desc = add_btn.text.strip() or add_btn.get_attribute("aria-label") or "FAB"
        except StaleElementReferenceException:
            btn_desc = "FAB"
        print(f"  Clicking: '{btn_desc}'")
        click(driver, add_btn)
        time.sleep(3); wait(driver)
        s = ss(driver, "add_emp_after_click")

        # Check for dialog/modal
        dialogs = [d for d in driver.find_elements(By.CSS_SELECTOR, "[role='dialog'], [class*='modal'], [class*='Modal'], [class*='dialog'], [class*='Dialog']") if d.is_displayed()]
        if dialogs:
            inputs = [i for i in dialogs[0].find_elements(By.CSS_SELECTOR, "input:not([type='hidden']), select, textarea") if i.is_displayed()]
            if inputs:
                log("Add employee dialog", "PASS", f"Dialog with {len(inputs)} inputs")
                fill_add_form(driver, inputs)
                return

        # Check page for form inputs
        inputs = [i for i in driver.find_elements(By.CSS_SELECTOR, "input:not([type='hidden']), select, textarea") if i.is_displayed()]
        hs_now = headings(driver)
        url_now = driver.current_url

        # Exclude the search/filter inputs on employee list (only 1-2)
        if len(inputs) >= 4:
            log("Add employee form", "PASS", f"{len(inputs)} inputs")
            fill_add_form(driver, inputs)
            return
        else:
            log("Add employee form", "FAIL", f"Only {len(inputs)} inputs after clicking '{btn_desc}'. URL: {url_now}")
            bug("[High] Add Employee button (FAB) does not open a creation form",
                f"## Description\nClicking the add button (FAB at bottom-right) on /employees does not open a form to create a new employee.\n\n## Steps\n1. Login as Org Admin\n2. Go to /employees\n3. Click the floating action button (bottom-right)\n\n## Expected\nA form/dialog to add new employee.\n\n## Actual\nNo form appears. Only {len(inputs)} inputs visible (search/filter). URL: {url_now}\nHeadings: {hs_now}", s)
    else:
        s = ss(driver, "add_emp_no_btn")
        log("Add employee", "FAIL", "No add button or working URL")
        bug("[Medium] No 'Add Employee' button on Employee Directory",
            "## Description\nNo button to add a new employee found on /employees.\n\n## Steps\n1. Login as Org Admin\n2. Go to /employees\n3. Look for Add/New/Create button\n\n## Expected\nAdd Employee button.\n\n## Actual\nNot found.", s)


def fill_add_form(driver, inputs):
    filled = []
    for inp in inputs:
        try:
            nm = (inp.get_attribute("name") or "").lower()
            ph = (inp.get_attribute("placeholder") or "").lower()
            lb = nm + " " + ph
            if any(w in lb for w in ["first", "fname"]):
                inp.clear(); inp.send_keys("Test"); filled.append("first_name")
            elif any(w in lb for w in ["last", "lname"]):
                inp.clear(); inp.send_keys("Employee"); filled.append("last_name")
            elif "email" in lb or "mail" in lb:
                inp.clear(); inp.send_keys("test.emp@technova.in"); filled.append("email")
            elif "phone" in lb or "mobile" in lb:
                inp.clear(); inp.send_keys("9876543210"); filled.append("phone")
        except:
            pass

    ss(driver, "add_emp_filled")
    log("Add employee fill", "PASS" if filled else "WARN", f"Filled: {filled}")

    # Try submit to check validation
    sub = None
    for b in driver.find_elements(By.TAG_NAME, "button"):
        t = (b.text or "").lower()
        if b.is_displayed() and any(w in t for w in ["save", "submit", "create", "add", "invite", "next"]):
            sub = b; break
    if not sub:
        try:
            sub = driver.find_element(By.CSS_SELECTOR, "button[type='submit']")
        except:
            pass

    if sub:
        click(driver, sub)
        time.sleep(2)
        s = ss(driver, "add_emp_submit")
        errs = [e for e in driver.find_elements(By.CSS_SELECTOR, "[class*='error'], [class*='invalid'], .text-danger, [role='alert']") if e.is_displayed() and e.text.strip()]
        if errs or page_has(driver, "required", "please enter", "mandatory"):
            log("Add emp validation", "PASS", f"{len(errs)} validation msgs")
        elif page_has(driver, "success", "created", "added"):
            log("Add emp submit", "PASS", "Success message")
        else:
            log("Add emp validation", "WARN", "No clear validation or success")
    else:
        log("Add emp submit btn", "WARN", "No submit button found")


# ── ATTENDANCE DASHBOARD ────────────────────────────────────────────────
def test_attendance(driver):
    print("\n=== ATTENDANCE DASHBOARD ===")
    goto(driver, "/attendance")
    s = ss(driver, "attendance")
    hs = headings(driver)
    bt = body_text(driver)

    if "Attendance Dashboard" in bt or any("attendance" in h.lower() for h in hs):
        log("Attendance page loads", "PASS", f"Headings: {[h for h in hs if 'attend' in h.lower()]}")
    elif "Welcome back" in bt or "Dashboard" in hs:
        log("Attendance page loads", "FAIL", "/attendance redirects to main dashboard instead of attendance")
        bug("[High] /attendance redirects to main dashboard",
            "## Description\nNavigating to /attendance shows the main dashboard instead of the Attendance Dashboard.\n\n## Steps\n1. Login as Org Admin\n2. Go to /attendance\n\n## Expected\nAttendance Dashboard with stats (Present, Absent, Late, etc.) and attendance list.\n\n## Actual\nMain welcome dashboard shown instead.", s)
        return
    else:
        log("Attendance page loads", "WARN", f"Unclear. Headings: {hs}")

    # Check stats
    if any(w in bt.lower() for w in ["present", "absent", "late", "total employee", "on leave"]):
        log("Attendance stats", "PASS", "Stats visible")
    else:
        log("Attendance stats", "WARN", "No attendance stats")

    # Check table
    rows = driver.find_elements(By.CSS_SELECTOR, "table tbody tr")
    if rows:
        log("Attendance table", "PASS", f"{len(rows)} entries")
        # Check columns
        ths = [th.text.strip() for th in driver.find_elements(By.CSS_SELECTOR, "table thead th") if th.text.strip()]
        print(f"  Columns: {ths}")
    else:
        log("Attendance table", "WARN", "No table rows")

    # Check for date filter/navigation
    date_els = driver.find_elements(By.CSS_SELECTOR, "input[type='date'], [class*='date-picker'], [class*='DatePicker']")
    if date_els:
        log("Attendance date filter", "PASS", "Date picker found")
    else:
        log("Attendance date filter", "WARN", "No date picker")


# ── ATTENDANCE VIEWS ────────────────────────────────────────────────────
def test_att_views(driver):
    print("\n=== ATTENDANCE VIEWS ===")
    # Check if still on attendance page
    if "attendance" not in driver.current_url.lower():
        goto(driver, "/attendance")

    # Look for view toggle buttons
    view_btns = []
    for el in driver.find_elements(By.CSS_SELECTOR, "button, [role='tab'], a"):
        txt = (el.text or "").strip().lower()
        if el.is_displayed() and txt and any(w in txt for w in ["calendar", "list", "table", "daily", "weekly", "monthly", "summary", "detailed", "report"]):
            view_btns.append((el, txt))

    if view_btns:
        for el, txt in view_btns[:4]:
            try:
                click(driver, el); time.sleep(2)
                ss(driver, f"att_view_{txt.replace(' ', '_')[:20]}")
                log(f"Attendance view: {txt}", "PASS")
            except Exception as e:
                log(f"Attendance view: {txt}", "FAIL", str(e)[:60])
    else:
        ss(driver, "att_no_views")
        log("Attendance views", "WARN", "No calendar/list/monthly view toggles")


# ── CLOCK IN ────────────────────────────────────────────────────────────
def test_clock_in(driver):
    print("\n=== CLOCK IN ===")
    # Check attendance page for clock-in button
    if "attendance" not in driver.current_url.lower():
        goto(driver, "/attendance")

    clock_btn = None
    for el in driver.find_elements(By.CSS_SELECTOR, "button, a"):
        txt = (el.text or "").strip().lower()
        if el.is_displayed() and any(w in txt for w in [
            "clock in", "clock-in", "check in", "check-in", "punch in", "mark attendance",
        ]):
            clock_btn = el; break

    if clock_btn:
        ss(driver, "clockin_found")
        click(driver, clock_btn)
        time.sleep(3)
        ss(driver, "clockin_result")
        log("Clock in", "PASS", f"Button '{clock_btn.text.strip()}' clicked")
        return

    # Try the dashboard
    goto(driver, "/")
    time.sleep(2)
    for el in driver.find_elements(By.CSS_SELECTOR, "button, a"):
        txt = (el.text or "").strip().lower()
        if el.is_displayed() and any(w in txt for w in ["clock in", "check in", "punch in", "mark attendance"]):
            clock_btn = el; break

    if clock_btn:
        ss(driver, "clockin_dashboard")
        click(driver, clock_btn); time.sleep(3)
        ss(driver, "clockin_dashboard_result")
        log("Clock in (dashboard)", "PASS", f"'{clock_btn.text.strip()}'")
        return

    # Try /attendance/daily-checkin or similar
    for path in ["/wellness/daily-checkin", "/daily-checkin", "/attendance/checkin"]:
        goto(driver, path)
        bt = body_text(driver).lower()
        if "check" in bt and ("daily" in bt or "attendance" in bt or "how" in bt):
            s = ss(driver, "daily_checkin_page")
            log("Daily Check-in page", "PASS", f"Found at {path}")
            # Look for submit
            for b in driver.find_elements(By.TAG_NAME, "button"):
                if b.is_displayed() and any(w in (b.text or "").lower() for w in ["submit", "check in", "save"]):
                    click(driver, b); time.sleep(2)
                    ss(driver, "daily_checkin_submit")
                    log("Daily Check-in submit", "PASS")
                    return
            return

    s = ss(driver, "clockin_missing")
    log("Clock in", "WARN", "No clock-in/check-in button found")
    bug("[Medium] No clock-in / check-in button available",
        "## Description\nNo clock-in or check-in button found on Attendance page or Dashboard.\n\n## Steps\n1. Login as Org Admin\n2. Check /attendance for clock-in button\n3. Check dashboard\n\n## Expected\nClock-in button to mark attendance.\n\n## Actual\nNo such button.", s)


# ── ATTENDANCE REGULARIZATION ───────────────────────────────────────────
def test_regularization(driver):
    print("\n=== ATTENDANCE REGULARIZATION ===")
    found = False

    for path in ["/attendance/regularization", "/regularization", "/attendance/requests",
                 "/attendance-regularization", "/attendance/corrections"]:
        goto(driver, path)
        bt = body_text(driver).lower()
        hs = headings(driver)
        if "regulari" in bt or "correction" in bt or any("regulari" in h.lower() for h in hs):
            s = ss(driver, "regularization")
            log("Attendance regularization", "PASS", f"Found at {path}")
            found = True
            break
        if "welcome back" in bt or "Welcome" in " ".join(hs):
            continue  # dashboard redirect

    if not found:
        # Try from attendance page
        goto(driver, "/attendance")
        for el in driver.find_elements(By.CSS_SELECTOR, "a, button"):
            txt = (el.text or "").strip().lower()
            if el.is_displayed() and ("regulari" in txt or "correction" in txt or "request" in txt):
                click(driver, el); time.sleep(3)
                s = ss(driver, "regularization")
                log("Regularization (from attendance)", "PASS", f"Link: '{txt}'")
                found = True; break

    if not found:
        s = ss(driver, "regularization_missing")
        log("Attendance regularization", "WARN", "Not found")
        bug("[Low] Attendance regularization page not accessible",
            "## Description\nCannot find attendance regularization page. Tried direct URLs and links from attendance page.\n\n## Steps\n1. Login as Org Admin\n2. Try /attendance/regularization, /regularization, etc.\n3. Check /attendance for regularization link\n\n## Expected\nRegularization page to submit corrections.\n\n## Actual\nPage not found.", s)


# ── SHIFTS ──────────────────────────────────────────────────────────────
def test_shifts(driver):
    print("\n=== SHIFTS PAGE ===")
    found = False

    for path in ["/shifts", "/attendance/shifts", "/settings/shifts", "/shift-management"]:
        goto(driver, path)
        bt = body_text(driver)
        hs = headings(driver)
        # Check if it's actually the shifts page and not dashboard
        if "Welcome back" in bt or any("welcome" in h.lower() for h in hs):
            print(f"  {path} -> redirected to dashboard")
            continue
        if "shift" in bt.lower() or any("shift" in h.lower() for h in hs):
            s = ss(driver, "shifts_page")
            log("Shifts page", "PASS", f"Found at {path}")
            found = True
            break

    if not found:
        # Check sidebar or attendance sublinks
        goto(driver, "/attendance")
        for el in driver.find_elements(By.CSS_SELECTOR, "a, button, [role='tab']"):
            txt = (el.text or "").strip().lower()
            if el.is_displayed() and "shift" in txt:
                click(driver, el); time.sleep(3)
                s = ss(driver, "shifts_from_att")
                log("Shifts (from attendance)", "PASS", f"Link: '{txt}'")
                found = True; break

    if not found:
        s = ss(driver, "shifts_missing")
        log("Shifts page", "FAIL", "Not found")
        bug("[High] Shifts management page not accessible",
            "## Description\nShifts page not found. /shifts redirects to dashboard. Other paths also fail.\n\n## Steps\n1. Login as Org Admin\n2. Try /shifts, /attendance/shifts, /settings/shifts\n\n## Expected\nShifts management page.\n\n## Actual\nAll paths redirect to dashboard or 404.", s)


# ── MAIN ────────────────────────────────────────────────────────────────
def main():
    print("=" * 60)
    print("EMP Cloud HRMS - E2E Test Suite (Final)")
    print(f"Target: {BASE}")
    print(f"Time: {datetime.now().isoformat()}")
    print("=" * 60)

    driver = mk_driver()
    try:
        if not do_login(driver):
            print("\n[ABORT] Login failed.")
            driver.quit()
            summary(); return

        test_emp_list(driver)
        test_emp_search(driver)
        test_emp_profile(driver)
        test_add_emp(driver)
        test_attendance(driver)
        test_att_views(driver)
        test_clock_in(driver)
        test_regularization(driver)
        test_shifts(driver)
    except Exception as e:
        print(f"\n[FATAL] {e}")
        traceback.print_exc()
        try: ss(driver, "fatal")
        except: pass
    finally:
        driver.quit()

    summary()


def summary():
    print("\n" + "=" * 60)
    print("TEST RESULTS SUMMARY")
    print("=" * 60)
    p = sum(1 for r in results if r["status"] == "PASS")
    f = sum(1 for r in results if r["status"] == "FAIL")
    w = sum(1 for r in results if r["status"] == "WARN")

    for r in results:
        line = f"  [{r['status']}] {r['test']}"
        if r["detail"]:
            line += f" -- {r['detail']}"
        print(line)

    print(f"\nTotal: {p+f+w}  |  PASS: {p}  |  FAIL: {f}  |  WARN: {w}")
    print(f"Screenshots: {SS_DIR}")

    if bugs:
        print(f"\nGitHub Issues Filed ({len(bugs)}):")
        for b in bugs:
            print(f"  {b['title']}")
            print(f"    {b['url']}")
    else:
        print("\nNo bugs filed.")
    print(f"\nFinished: {datetime.now().isoformat()}")


if __name__ == "__main__":
    main()
